# Generated by Django 2.2.13 on 2020-06-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200619_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsarticles',
            options={'ordering': ['-is_main']},
        ),
    ]
